projectName: full-workflow-demo
version: 0.1.0
lastUpdated: 2025-07-01T00:00:00
structure:
  type: single_package
  primaryLanguage: python
  directories:
    source: ["src"]
    tests: ["tests"]
    docs: ["docs"]
  entryPoints: ["src/main.py"]
  ignore: ["**/__pycache__/**", "**/.git/**", "**/venv/**"]
keyArtifacts:
  docs:
    - path: README.md
      purpose: Example workflow guide
features:
  wsde_collaboration: false
  dialectical_reasoning: false
  code_generation: true
  test_generation: true
  documentation_generation: true
  experimental_features: false
