# Branch protection configuration to prevent push-triggered workflows
# Only pull requests can update the main branch.

branch_protection:
  main:
    required_pull_request_reviews:
      required_approving_review_count: 1
    allow_force_pushes: false
    allow_deletions: false
