- id: devsynth-align
  name: devsynth align
  description: "Check SDLC artifact alignment with devsynth"
  entry: devsynth align --quiet
  language: system
  pass_filenames: false
- id: check-frontmatter
  name: check frontmatter formatting
  description: "Detect frontmatter formatting issues in Markdown files"
  entry: python scripts/fix_frontmatter.py --check
  language: system
  pass_filenames: false
