- id: devsynth-align
  name: devsynth align
  description: "Check SDLC artifact alignment with devsynth"
  entry: devsynth align --quiet
  language: system
  pass_filenames: false
- id: check-frontmatter
  name: check frontmatter formatting
  description: "Detect frontmatter formatting issues in Markdown files"
  entry: python scripts/fix_frontmatter.py --check
  language: system
  pass_filenames: false
- id: check-internal-links
  name: check internal links
  description: "Detect broken internal links in Markdown files"
  entry: python scripts/check_internal_links.py
  language: system
  pass_filenames: false
- id: fix-code-blocks
  name: fix code blocks
  description: "Ensure Markdown code blocks are formatted correctly"
  entry: python scripts/fix_code_blocks.py --check
  language: system
  pass_filenames: false
- id: find-syntax-errors
  name: find syntax errors
  description: "Detect Python syntax errors across the repository"
  entry: python scripts/find_syntax_errors.py
  language: system
  pass_filenames: false
- id: verify-mvuu-references
  name: verify mvuu references
  description: "Ensure MVUU references are valid"
  entry: python scripts/verify_mvuu_references.py
  language: system
  pass_filenames: false
- id: verify-requirements-traceability
  name: verify requirements traceability
  description: "Ensure requirements traceability matrix links requirements to code and tests"
  entry: poetry run python scripts/verify_requirements_traceability.py
  language: system
  pass_filenames: false
  files: ^docs/requirements_traceability.md$
- id: spec-or-test-updates
  name: warn on missing spec or test updates
  description: "Ensure code changes include specification or test updates"
  entry: python scripts/check_spec_or_test_updates.py
  language: system
  pass_filenames: false
- id: update-traceability
  name: update traceability
  description: "Update traceability data"
  entry: python scripts/update_traceability.py
  language: system
  pass_filenames: false
- id: policy-audit
  name: policy audit
  description: "Scan configs and code for policy violations"
  entry: python scripts/policy_audit.py
  language: system
  pass_filenames: false
