version: '3.8'

services:
  # Main DevSynth application
  devsynth:
    build:
      context: .
      target: development
    volumes:
      - .:/opt/pysetup
      - ~/.devsynth:/home/devsynth/.devsynth
      - ./logs:/var/log/devsynth
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DEVSYNTH_ENV=development
      - DEVSYNTH_LOG_LEVEL=DEBUG
      - DEVSYNTH_LOG_DIR=/var/log/devsynth
      - DEVSYNTH_LLM_PROVIDER=openai
    networks:
      - devsynth-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped


  # Development tools
  dev-tools:
    build:
      context: .
      target: development
    volumes:
      - .:/opt/pysetup
    command: /bin/bash -c "tail -f /dev/null"
    env_file:
      - .env
    networks:
      - devsynth-network
    profiles:
      - tools
    healthcheck:
      test: ["CMD", "true"]
      interval: 1m
      timeout: 10s
      retries: 3

  # Test runner
  test-runner:
    build:
      context: .
      target: testing
    volumes:
      - .:/opt/pysetup
    environment:
      - DEVSYNTH_ENV=testing
    env_file:
      - .env
    networks:
      - devsynth-network
    profiles:
      - test
    healthcheck:
      test: ["CMD", "true"]
      interval: 1m
      timeout: 10s
      retries: 3

  # Optional ChromaDB service for persistent vector storage
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chromadb-data:/chroma
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - "8001:8000"
    networks:
      - devsynth-network
    profiles:
      - memory

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - devsynth-network
    profiles:
      - monitoring


networks:
  devsynth-network:
    name: devsynth-network
volumes:
  chromadb-data:
    name: devsynth-chromadb-data
