version: '3.8'

services:
  # Main DevSynth application
  devsynth:
    build:
      context: .
      target: development
    volumes:
      - .:/opt/pysetup
      - ~/.devsynth:/home/devsynth/.devsynth
      - ./logs:/var/log/devsynth
    ports:
      - "8000:8000"
    environment:
      - DEVSYNTH_ENV=development
      - DEVSYNTH_LOG_LEVEL=DEBUG
      - DEVSYNTH_LOG_DIR=/var/log/devsynth
      - DEVSYNTH_LLM_PROVIDER=openai
    networks:
      - devsynth-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped


  # Development tools
  dev-tools:
    build:
      context: .
      target: development
    volumes:
      - .:/opt/pysetup
    command: /bin/bash -c "tail -f /dev/null"
    networks:
      - devsynth-network
    profiles:
      - tools

  # Test runner
  test-runner:
    build:
      context: .
      target: testing
    volumes:
      - .:/opt/pysetup
    environment:
      - DEVSYNTH_ENV=testing
    networks:
      - devsynth-network
    profiles:
      - test


networks:
  devsynth-network:
    name: devsynth-network