version: '3.8'

services:
  devsynth-api:
    image: ghcr.io/devsynth/devsynth:${DEVSYNTH_IMAGE_TAG:-latest}
    build:
      context: .
      target: production
    command: uvicorn devsynth.api:app --host 0.0.0.0 --port 8000
    environment:
      - DEVSYNTH_ENV=production
      - DEVSYNTH_LOG_LEVEL=INFO
      - DEVSYNTH_LOG_DIR=/var/log/devsynth
    volumes:
      - devsynth-data:/data/devsynth
      - ./logs:/var/log/devsynth
    ports:
      - "8000:8000"
    networks:
      - devsynth-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  devsynth-cli:
    image: ghcr.io/devsynth/devsynth-cli:${DEVSYNTH_IMAGE_TAG:-latest}
    build:
      context: .
      target: production
    command: devsynth
    environment:
      - DEVSYNTH_ENV=production
      - DEVSYNTH_LOG_DIR=/var/log/devsynth
    volumes:
      - devsynth-data:/data/devsynth
      - ./logs:/var/log/devsynth
    networks:
      - devsynth-network
    profiles:
      - cli


  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - devsynth-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - devsynth-network

  # CI utilities
  publish:
    build:
      context: .
      target: production
    entrypoint: ["/bin/bash", "scripts/deployment/publish_image.sh", "${DEVSYNTH_IMAGE_TAG:-latest}", "devsynth-api"]
    environment:
      - COMPOSE_FILE=docker-compose.production.yml
    profiles:
      - ci

  rollback:
    build:
      context: .
      target: production
    entrypoint: ["/bin/bash", "scripts/deployment/rollback.sh", "${DEVSYNTH_ROLLBACK_TAG:-latest}", "production"]
    profiles:
      - ci

volumes:
  grafana-data:
    name: devsynth-grafana-data
  devsynth-data:
    name: devsynth-app-data

networks:
  devsynth-network:
    name: devsynth-network
