site_name: DevSynth
repo_url: https://github.com/ravenoak/devsynth
repo_name: ravenoak/devsynth
edit_uri: edit/main/docs/

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes # To make sections clickable
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting_started/quick_start_guide.md
    - Installation: getting_started/installation.md
    - Basic Usage: getting_started/basic_usage.md
    - Troubleshooting: getting_started/troubleshooting.md
  - User Guides:
    - Overview: user_guides/index.md
    - User Guide: user_guides/user_guide.md
    - CLI Command Reference: user_guides/cli_command_reference.md
  - Developer Guides:
    - Overview: developer_guides/index.md
    - Onboarding Guide: developer_guides/onboarding.md
    - Contributing: developer_guides/contributing.md
    - Development Setup: developer_guides/development_setup.md
    - Testing Guide: developer_guides/testing.md
    - Diagnostics: developer_guides/diagnostics.md
    - Resources Matrix: resources_matrix.md
    - Code Style: developer_guides/code_style.md
    - Documentation Style Guide: policies/documentation_style_guide.md
    - Repository Structure: repo_structure.md
  - Architecture:
    - Overview: architecture/overview.md
    - Hexagonal Architecture: architecture/hexagonal_architecture.md
    - Agent System: architecture/agent_system.md
    - Memory System: architecture/memory_system.md
    - Provider System: architecture/provider_system.md
    - Dialectical Reasoning: architecture/dialectical_reasoning.md
    - EDRR Framework: architecture/edrr_framework.md
    - WSDE Agent Model: architecture/wsde_agent_model.md
    - Docs Consolidation Plan: architecture/docs_consolidation_plan.md
  - Technical Reference:
    - Overview: technical_reference/index.md
    - API Reference: technical_reference/api_reference/index.md
    - Error Handling: technical_reference/error_handling.md
    - Performance: technical_reference/performance.md
    - EDRR Methodology: technical_reference/expand_differentiate_refine_retrospect.md
  - Rationales:
    - Test Fixes (Dialectical Review): rationales/test_fixes.md
  - Project Analysis:
    - Overview: analysis/index.md
    - Executive Summary: analysis/executive_summary.md
    - Critical Recommendations: analysis/critical_recommendations.md
    - Technical Deep Dive: analysis/technical_deep_dive.md
    - Dialectical Evaluation: analysis/dialectical_evaluation.md
    - Project Inventory: analysis/inventory.md
    - Flaky Case Log: analysis/flaky_case_log.md
  - Implementation Status:
    - Overview: implementation/index.md
    - Feature Status Matrix: implementation/feature_status_matrix.md
    - EDRR Assessment: implementation/edrr_assessment.md
    - Phase 1 Summary: implementation/phase1_month1_summary.md
    - WSDE Validation: implementation/wsde_validation.md
  - Specifications:
    - Overview: specifications/index.md
    - DevSynth MVP Specification: specifications/devsynth_specification_mvp_updated.md
    - EDRR Cycle Specification: specifications/edrr_cycle_specification.md
    - WSDE Interaction Specification: specifications/wsde_interaction_specification.md
    - Hybrid Memory Architecture: specifications/hybrid_memory_architecture.md
  - Policies:
    - Overview: policies/index.md
    - Requirements Policy: policies/requirements.md
    - Design Policy: policies/design.md
    - Development Policy: policies/development.md
    - Testing Policy: policies/testing.md
    - Deployment Policy: policies/deployment.md
    - Maintenance Policy: policies/maintenance.md
    - Cross-Cutting Concerns: policies/cross_cutting.md
    - SDLC Policies for Agentic LLM Projects: policies/sdlc_policies_for_agentic_llm_projects.md
  - Roadmap:
    - Overview: roadmap/index.md
    - Development Plan: roadmap/development_plan.md
    - Development Status: roadmap/development_status.md
    - Documentation Policies: roadmap/documentation_policies.md
    - Testing Infrastructure: specifications/testing_infrastructure.md
  - Release:
    - Release Notes (0.1.0‑alpha.1): release/0.1.0-alpha.1.md
    - Release Playbook: release/release_playbook.md
    - Readiness Gates: release/release_readiness.md
    - Post‑release Validation: release/post_release_validation.md
  - Changelog: CHANGELOG.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
  # Python specific for mkdocstrings
  - tables
  - fenced_code
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_root_heading: true
            show_source: true
  - literate-nav:
      nav_file: SUMMARY.md # If you use literate-nav
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py # If you use this for API docs
  - include-markdown # If you use this plugin

extra_css:
  - stylesheets/extra.css # For any custom styling

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ravenoak
  version:
    provider: mike # If using mkdocs-mike for versioning
    default_version: latest

# Copyright
copyright: Copyright &copy; 2024-2025 Raven Oak
