projectName: calculator-example
version: 0.1.0
structure:
  type: single_package
  primaryLanguage: python
  directories:
    source: ["src"]
    tests: ["tests"]
    docs: ["."]
features:
  code_generation: true
  test_generation: true
