[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "types-responses"
version = "0.0.0"
description = "Typing stubs for the responses library"
requires-python = ">=3.12"
