from typing import Any

class TinyDB:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def insert(self, document: Any) -> int: ...
    def table(self, name: str | None = ...) -> TinyDB: ...
    def all(self) -> list[Any]: ...
    def search(self, cond: Any) -> list[Any]: ...
    def get(self, cond: Any | None = ...) -> Any: ...
    def remove(self, cond: Any | None = ...) -> int: ...
    def close(self) -> None: ...

class Query:
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

__all__ = ["TinyDB", "Query"]
