from typing import Any

class Cursor:
    def first(self) -> bool: ...
    def next(self) -> bool: ...
    def key(self) -> bytes: ...
    def value(self) -> bytes: ...
    def set_range(self, key: bytes) -> bool: ...
    def close(self) -> None: ...

class Transaction:
    def commit(self) -> None: ...
    def abort(self) -> None: ...
    def put(self, key: bytes, value: bytes, *, db: Any | None = ...) -> bool: ...
    def get(self, key: bytes, *, db: Any | None = ...) -> bytes | None: ...
    def delete(self, key: bytes, *, db: Any | None = ...) -> bool: ...
    def cursor(self, db: Any | None = ...) -> Cursor: ...

class Environment:
    def begin(self, *, write: bool = ...) -> Transaction: ...
    def open_db(self, name: bytes | None = ...) -> Any: ...
    def close(self) -> None: ...

def open(path: str, *args: Any, **kwargs: Any) -> Environment: ...

__all__ = ["Cursor", "Transaction", "Environment", "open"]
