[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "types-pytest-bdd"
version = "0.0.0"
description = "Typing stubs for pytest-bdd"
requires-python = ">=3.12"
