version: '3.8'

services:
  devsynth:
    build:
      context: ..
      target: development
    volumes:
      - ..:/opt/pysetup
      - ~/.devsynth:/home/devsynth/.devsynth
    ports:
      - "8000:8000"
    environment:
      - DEVSYNTH_ENV=development
      - DEVSYNTH_LOG_LEVEL=DEBUG
      - DEVSYNTH_LLM_PROVIDER=openai
    security_opt:
      - no-new-privileges:true
    networks:
      - devsynth-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped


networks:
  devsynth-network:
    name: devsynth-network
