name: Check Internal Links

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.md'
      - 'scripts/check_internal_links.py'
      - '.github/workflows/check_internal_links.yml'
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,docs]
      - name: Check internal links
        run: python scripts/check_internal_links.py
