name: Container Build

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'docker-compose*'
      - '.github/workflows.disabled/container_build.yml'
  push:
    branches: [ main, master ]
    paths:
      - 'Dockerfile'
      - 'docker-compose*'
      - '.github/workflows.disabled/container_build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: devsynth:ci
