name: Dependency Check

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/dependency_check.yml"
      - "scripts/dependency_safety_check.py"
  workflow_dispatch:

jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry safety
          poetry install --with dev,docs --all-extras --no-root

      - name: Run dependency safety check
        run: python scripts/dependency_safety_check.py
      - name: Run project checks
        # Runs tests and documentation checks; fails if any script exits non-zero
        run: |
          poetry run python scripts/run_all_tests.py
          poetry run python scripts/check_internal_links.py
          poetry run python scripts/fix_code_blocks.py --check
