name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --with dev --all-extras --no-interaction
      - name: Run project checks
        # Runs tests and documentation checks; fails if any script exits non-zero
        run: |
          poetry run python scripts/run_all_tests.py
          poetry run python scripts/check_internal_links.py
          poetry run python scripts/fix_code_blocks.py --check

  security-scan:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Run pip-audit
        run: pip-audit || true

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'
      - name: Deploy to cluster
        run: kubectl apply -f deployment/k8s/
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
