name: Static Analysis

on:
  pull_request:
    paths:
      - '**/*.py'
      - '.github/workflows/static_analysis.yml'
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,docs] bandit
      - name: Run Bandit
        run: bandit -r src -ll
      - name: Run project checks
        # Runs tests and documentation checks; fails if any script exits non-zero
        run: |
          python scripts/run_all_tests.py
          python scripts/check_internal_links.py
          python scripts/fix_code_blocks.py --check
