name: Test Results

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/test_results.yml'
      - 'pytest.ini'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'
      - '.github/workflows/test_results.yml'
      - 'pytest.ini'
  workflow_dispatch:

jobs:
  test-results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
          
      - name: Run unit tests with JUnit report
        run: |
          mkdir -p test-results/unit
          poetry run pytest tests/unit/ --junitxml=test-results/unit/results.xml
          
      - name: Run integration tests with JUnit report
        run: |
          mkdir -p test-results/integration
          poetry run pytest tests/integration/ --junitxml=test-results/integration/results.xml
          
      - name: Run behavior tests with JUnit report
        run: |
          mkdir -p test-results/behavior
          poetry run pytest tests/behavior/ --junitxml=test-results/behavior/results.xml

      - name: Run property tests with JUnit report
        run: |
          mkdir -p test-results/property
          poetry run pytest tests/property/ --junitxml=test-results/property/results.xml
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml
          
      - name: Generate HTML test report
        if: always()
        run: |
          pip install pytest-html
          poetry run pytest tests/ --html=test-report.html --self-contained-html
          
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            test-results/
            test-report.html