name: Verify Test Organization

on:
  push:
    branches: [ main, master ]
    paths:
      - 'tests/**'
      - '.github/workflows.disabled/verify_test_organization.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'tests/**'
      - '.github/workflows.disabled/verify_test_organization.yml'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run test organization checks
        run: |
          python tests/verify_test_organization.py
