# DevSynth Default Configuration
# This file contains default settings that apply to all environments

# Application settings
application:
  name: DevSynth
  version: 0.1.0
  description: AI-driven development platform

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null  # Log to stdout by default

# Memory system configuration
memory:
  default_store: kuzu
  memory_file_path: ./.devsynth/memory
  kuzu_embedded: true
  stores:
    chromadb:
      enabled: true
      collection_name: devsynth
      distance_function: cosine
      persist_directory: ./.devsynth/chromadb
      host: null
      port: 8000
    kuzu:
      persist_directory: ./.devsynth/kuzu
    faiss:
      enabled: false
      index_file: ./.devsynth/faiss/index.bin
      dimension: 1536

# LLM provider configuration
llm:
  default_provider: openai
  providers:
    openai:
      enabled: true
      model: gpt-4
      temperature: 0.7
      max_tokens: 4096
      timeout: 60
    anthropic:
      enabled: false
      model: claude-2
      temperature: 0.7
      max_tokens: 4096
      timeout: 60
    local:
      enabled: false
      model_path: null
      context_length: 4096
    lmstudio:
      enabled: false  # Disabled by default, enable with DEVSYNTH_RESOURCE_LMSTUDIO_AVAILABLE=true
      api_base: http://127.0.0.1:1234
      model: null  # Auto-select first available model
      max_tokens: 4096
      temperature: 0.7
      timeout: 60
      auto_select_model: true
      max_retries: 3
      failure_threshold: 3
      recovery_timeout: 60
      call_timeout: 10.0

# Agent configuration
agents:
  max_agents: 5
  default_timeout: 300
  memory_context_size: 10
  collaboration:
    enabled: true
    consensus_threshold: 0.7
    max_rounds: 3

# EDRR framework configuration
edrr:
  enabled: true
  default_phase: expand
  phase_transition:
    auto: true
    timeout: 600
  phases:
    expand:
      divergence_factor: 0.8
      max_ideas: 10
    differentiate:
      comparison_depth: 3
      criteria_count: 5
    refine:
      detail_level: 3
      optimization_rounds: 2
    retrospect:
      learning_extraction: true
      pattern_recognition: true

# Security settings
security:
  input_validation: true
  sanitization: true
  rate_limiting:
    enabled: true
    max_requests: 100
    period: 60  # seconds
  encryption:
    at_rest: false
    key: null
    in_transit: true
  tls:
    verify: true
    cert_file: null
    key_file: null
    ca_file: null

# Performance settings
performance:
  cache:
    enabled: true
    ttl: 3600  # seconds
  concurrency:
    max_workers: 4
    timeout: 300  # seconds

# GUI settings
gui:
  enabled: false

# Formal verification settings
formalVerification:
  propertyTesting: false
  smtChecks: false

# Feature flags
features:
  wsde_collaboration: false
  dialectical_reasoning: false
  code_generation: false
  test_generation: false
  documentation_generation: false
  prompt_auto_tuning: false
  automatic_phase_transitions: false
  collaboration_notifications: false
