# DevSynth Development Configuration
# Overrides for development environment

# Application settings
application:
  name: DevSynth
  version: 0.1.0a1
  description: AI-driven development platform

# Agent configuration
agents:
  max_agents: 3
  default_timeout: 180

# EDRR framework configuration
edrr:
  enabled: true

# Logging configuration
logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"

# Memory system configuration
memory:
  default_store: kuzu
  stores:
    chromadb:
      enabled: true
      persist_directory: ./.devsynth/dev/chromadb
      host: null
      port: 8000
    kuzu:
      persist_directory: ./.devsynth/dev/kuzu

# LLM provider configuration
llm:
  default_provider: lmstudio  # Use LM Studio provider in development for testing
  providers:
    openai:
      enabled: false  # Disabled by default, set OPENAI_API_KEY to enable
      temperature: 0.8  # More creative in development
      max_tokens: 2048  # Smaller context to save tokens during development
    lmstudio:
      enabled: false  # Disabled by default, enable with DEVSYNTH_RESOURCE_LMSTUDIO_AVAILABLE=true
      api_base: http://127.0.0.1:1234
      model: null  # Auto-select first available model
      max_tokens: 2048  # Smaller context for development
      temperature: 0.8  # More creative in development
      timeout: 30  # Shorter timeout for development
      auto_select_model: true
      max_retries: 2  # Fewer retries in development
      failure_threshold: 2
      recovery_timeout: 30
      call_timeout: 5.0

# Security settings
security:
  input_validation: true
  rate_limiting:
    enabled: false  # Disable rate limiting in development
  encryption:
    at_rest: false
    in_transit: false  # No TLS in development

# Performance settings
performance:
  cache:
    ttl: 300  # Shorter cache TTL for development
  concurrency:
    max_workers: 2  # Fewer workers in development

# Formal verification settings
formalVerification:
  propertyTesting: false
  smtChecks: false

# Feature flags - enable all in development
features:
  wsde_collaboration: true
  dialectical_reasoning: true
  code_generation: true
  test_generation: true
  documentation_generation: true
  experimental_features: true  # Only in development
  automatic_phase_transitions: true
  collaboration_notifications: true
  prompt_auto_tuning: false
