apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: devsynth
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: devsynth-api
        static_configs:
          - targets: ['devsynth-api:8000']
