name: CI - Lint, Type, and Security Checks

on:
  workflow_dispatch:
  # TODO: Re-enable push/pull_request triggers after tagging v0.1.0-alpha.1 (docs/tasks.md item 10.1)
jobs:
  lint-type-security:
    name: Lint/Type/Security (Python 3.12)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache Poetry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Cache pip wheels
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: pip-${{ runner.os }}-${{ steps.python-setup.outputs.python-version || '3.12' }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Install dependencies (dev group)
        run: |
          poetry install --with dev --extras minimal

      - name: Black (check)
        run: poetry run black --check .

      - name: isort (check-only)
        run: poetry run isort --check-only .

      - name: Flake8
        run: poetry run flake8 src/ tests/

      - name: Mypy (strict)
        run: poetry run mypy src/devsynth

      - name: Bandit (security)
        run: poetry run bandit -r src/devsynth -x tests

      - name: Safety (vuln DB)
        run: poetry run safety check --full-report
