name: CI

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev,docs
      - name: Verify Poetry virtualenv
        run: |
          venv_path=$(poetry env info --path)
          if [ -z "$venv_path" ]; then
            echo "Poetry virtualenv path not found" >&2
            exit 1
          fi
          echo "Using virtualenv at $venv_path"
      - name: Lint commit messages
        run: |
          git fetch origin main
          python scripts/commit_linter.py --range origin/main..HEAD
      - name: Verify MVUU references
        run: |
          python scripts/verify_mvuu_references.py origin/main..HEAD
      - name: Check test ReqIDs
        run: |
          python scripts/check_reqid.py --rev-range origin/main..HEAD
      - name: Verify test markers
        run: |
          poetry run python scripts/verify_test_markers.py
      - name: Run Bandit
        run: |
          poetry run bandit -q -r src
      - name: Run Safety
        run: |
          python scripts/dependency_safety_check.py
      - name: Build package
        run: |
          poetry build
      - name: Run tests
        run: |
          poetry run pytest
