name: CI

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev,docs
          venv_path=$(poetry env info --path 2>/dev/null || true)
          if [ -z "$venv_path" ]; then
            echo "Poetry virtualenv path not found" >&2
            exit 1
          fi
          echo "Using virtualenv at $venv_path"
      - name: Install Task
        run: |
          if ! command -v task >/dev/null 2>&1; then
            TASK_BIN_DIR="$HOME/.local/bin"
            mkdir -p "$TASK_BIN_DIR"
            curl -sSL https://taskfile.dev/install.sh | bash -s -- -b "$TASK_BIN_DIR"
            echo "$TASK_BIN_DIR" >> $GITHUB_PATH
          fi
      - name: Task version
        run: task --version
      - name: Lint commit messages
        run: |
          git fetch origin main
          python scripts/commit_linter.py --range origin/main..HEAD
      - name: Verify MVUU references
        run: |
          python scripts/verify_mvuu_references.py origin/main..HEAD
      - name: Check test ReqIDs
        run: |
          python scripts/check_reqid.py --rev-range origin/main..HEAD
      - name: Verify test markers
        run: |
          poetry run python scripts/verify_test_markers.py
      - name: Task release prep
        run: task release:prep
      - name: Build package
        run: |
          poetry build
      - name: Run tests
        run: |
          poetry run pytest
