name: Commit Message Lint

on:
  workflow_dispatch:
  # TODO: Re-enable push/pull_request triggers after tagging v0.1.0-alpha.1 (docs/tasks.md item 10.1)
jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Determine base ref
        id: base
        shell: bash
        run: |
          BASE_REF="${GITHUB_BASE_REF:-main}"
          echo "base=$BASE_REF" >> "$GITHUB_OUTPUT"
      - name: Fetch base branch
        run: |
          git fetch origin ${{ steps.base.outputs.base }}
      - name: Lint commit messages
        run: |
          python scripts/commit_linter.py --range origin/${{ steps.base.outputs.base }}..HEAD
