name: Container Build

on:
  workflow_dispatch:
  # TODO: Re-enable push/pull_request triggers after tagging v0.1.0-alpha.1 (docs/tasks.md item 10.1)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,docs]
      - name: Run project checks
        # Runs tests and documentation checks; fails if any script exits non-zero
        run: |
          git fetch origin main
          python scripts/run_all_tests.py
          python scripts/check_internal_links.py
          python scripts/fix_code_blocks.py --check
          python scripts/check_reqid.py --rev-range origin/main..HEAD
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: devsynth:ci
