name: Dependency Check

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/dependency_check.yml"
      - "scripts/dependency_safety_check.py"
  workflow_dispatch:

jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry safety
          poetry install --no-root

      - name: Run dependency safety check
        run: python scripts/dependency_safety_check.py
