name: Dev Environment Check

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'
  workflow_dispatch:
  # Restored push/pull_request triggers after v0.1.0a1 tagging
jobs:
  dev-env:
    name: Verify Poetry dev environment (install + activation)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry --version

      - name: Install project with dev, docs, and all extras
        run: |
          poetry install --with dev,docs --all-extras

      - name: Verify environment activation and CLI availability
        env:
          DEVSYNTH_DISABLE_NETWORK: "1"
        run: |
          poetry run python -V
          poetry run devsynth --help
