name: Lint (Black, Isort, Flake8)

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/lint.yml'
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/lint.yml'
  workflow_dispatch: {}

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Style and lint checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.3'

      - name: Install dependencies (dev)
        run: |
          poetry env use 3.12
          poetry install --with dev --extras "tests" --no-interaction --no-ansi

      - name: Black (check)
        run: |
          poetry run black --version
          poetry run black --check .

      - name: Isort (check-only)
        run: |
          poetry run isort --version-number
          poetry run isort --check-only .

      - name: Flake8
        run: |
          poetry run flake8 src/ tests/
