name: Performance Benchmarks

on:
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Run project checks
        # Runs tests and documentation checks; fails if any script exits non-zero
        run: |
          git fetch origin main
          poetry run python scripts/run_all_tests.py
          poetry run python scripts/check_internal_links.py
          poetry run python scripts/fix_code_blocks.py --check
          poetry run python scripts/check_reqid.py --rev-range origin/main..HEAD

      - name: Run performance benchmarks
        run: |
          poetry run pytest tests/performance --benchmark-only --benchmark-save=benchmark

      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: performance-benchmarks
          path: .benchmarks
