name: Secret Scan (Gitleaks)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  gitleaks:
    name: Run Gitleaks secret scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for better scanning

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --verbose --redact
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
