name: Security Checks

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev --all-extras
      - name: Run static analysis
        run: poetry run pre-commit run --hook-stage push --all-files bandit safety
      - name: Enforce security policy
        env:
          DEVSYNTH_PRE_DEPLOY_APPROVED: "true"
        run: poetry run python scripts/security_audit.py
