name: Security Scans

on:
  workflow_dispatch:
  # TODO: Re-enable push/pull_request triggers after tagging v0.1.0-alpha.1 (docs/tasks.md item 10.1)
concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security:
    name: Bandit and Safety
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.3'

      - name: Cache pip wheels
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Poetry virtualenvs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dev dependencies
        run: |
          poetry env use 3.12
          poetry install --with dev --extras minimal

      - name: Bandit (security lint)
        run: poetry run bandit -r src/devsynth -x tests

      - name: Safety (vulnerability scan)
        env:
          SAFETY_DISABLE_TELEMETRY: '1'
        run: poetry run safety check --full-report
