name: Security Checks

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev --all-extras
      - name: Run policy gate
        env:
          DEVSYNTH_PRE_DEPLOY_APPROVED: "true"
        run: poetry run task policy:gate
      - name: Run security audit
        env:
          DEVSYNTH_PRE_DEPLOY_APPROVED: "true"
        run: |
          poetry run python scripts/security_audit.py --report security_audit.json
      - name: Upload security audit report
        uses: actions/upload-artifact@v4
        with:
          name: security_audit
          path: security_audit.json
      - name: Run dialectical audit
        run: |
          poetry run python scripts/dialectical_audit.py || true
      - name: Upload dialectical audit log
        uses: actions/upload-artifact@v4
        with:
          name: dialectical_audit
          path: dialectical_audit.log
