name: Verify Test Markers

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'
  workflow_dispatch:
  # Restored push/pull_request triggers after v0.1.0a1 tagging
permissions:
  contents: read

jobs:
  verify-markers:
    name: verify test speed markers discipline
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      # Ensure offline-safe defaults as per guidelines
      DEVSYNTH_OFFLINE: 'true'
      DEVSYNTH_PROVIDER: 'stub'
      DEVSYNTH_RESOURCE_LMSTUDIO_AVAILABLE: 'false'
      OPENAI_API_KEY: 'test-openai-key'
      DEVSYNTH_NO_FILE_LOGGING: '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.3'

      - name: Install dependencies (dev + tests minimal)
        run: |
          poetry install --with dev --extras minimal --extras tests

      - name: Verify test markers and generate report
        run: |
          poetry run python scripts/verify_test_markers.py --report --report-file test_markers_report.json

      - name: Upload test marker report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-markers-report
          path: |
            test_markers_report.json
          if-no-files-found: warn
